# Generated by Django 6.0.6 on 2026-06-23 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='category',
            field=models.ForeignKey(blank=True, help_text='If set, tracks spending only for this category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.category'),
        ),
    ]
